name: new one

on:
  workflow_dispatch:
  schedule:
    # Offsets the execution by 15 minutes to prevent simultaneous worker contention
    - cron: '15 */6 * * *'

jobs:
  run-bot-mobi:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run Mobi Bot with Maven
        env:
          GAME_ID_MOBI: ${{ secrets.GAME_ID_1 }}
          GAME_PASSWORD_MOBI: ${{ secrets.GAME_PASSWORD_1 }}
        run: mvn compile exec:java -Dexec.mainClass=Main2
